Update JSqlParserCC.jjt
JSQLParser/JSqlParser pull request #1338
Opened 2021-09-16 19:42 UTC by xiaoyunwu

support json operator in postgres

2021-09-17 00:07 UTC, manticore-projects commented
Greetings!

Thank you very much for the contribution, much appreciated.

Please would you also like to add a simple Unit Test Case testing this operator. It should prove that your SQL Statements are parsed and deparsed correctly. (I am especially worried about deparsing as you did not touch the Java Object Code yet.)

You can use the following template:
```java
package net.sf.jsqlparser.expression;

import net.sf.jsqlparser.JSQLParserException;
import net.sf.jsqlparser.test.TestUtils;
import org.junit.Test;

/**
 *
 * @author <a href="mailto:andreas@manticore-projects.com">Andreas Reichel</a>
 */
public class CastExpressionTest {
  @Test
  public void testCastToRowConstructorIssue1267() throws JSQLParserException {
    TestUtils.assertExpressionCanBeParsedAndDeparsed("CAST(ROW(dataid, value, calcMark) AS ROW(datapointid CHAR, value CHAR, calcMark CHAR))", true);
    TestUtils.assertExpressionCanBeParsedAndDeparsed("CAST(ROW(dataid, value, calcMark) AS testcol)", true);
  }
}
```

2021-09-17 01:05 UTC, manticore-projects commented
You can also add `fixes #1337` to the description of the PR (not the caption though) in order to link between issue and PR and auto-close when accepted.

2021-09-18 11:49 UTC, wumpz requested changes

2021-09-18 11:49 UTC, wumpz commented on src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
> +    | "@?" { result = new Matches(); }
The problem here is that this statement cannot be reconstructed since a Matches instance is printed as "*@@*". 
BTW what is the sematic of "*@?*"?

2022-09-11 06:47 UTC, manticore-projects commented
Greetings.

If this PR is still of interest, then please follow the recommendations here: https://manticore-projects.com/JSQLParser/contribution.html#amend-the-code

Otherwise I would like to suggest to close it as a stale PR.

2023-07-18 03:36 UTC, manticore-projects commented
Any feedback please? I would like top close this otherwise.

2023-09-12 09:04 UTC, manticore-projects commented
This thing is dead. Please resubmit properly when there is any serious interest.

2023-09-12 09:04 UTC, closed without merging