Add support for Hive dialect GROUPING SETS.
JSQLParser/JSqlParser pull request #1539
Opened 2022-05-19 13:05 UTC by qzchenwl

[Hive dialect](https://cwiki.apache.org/confluence/display/Hive/Enhanced+Aggregation%2C+Cube%2C+Grouping+and+Rollup#EnhancedAggregation,Cube,GroupingandRollup-GROUPINGSETSclause) requires all columns appear in GROUPING SETS clause to be in GROUP BY clause.

```
SELECT a, b, SUM( c ) FROM tab1 GROUP BY a, b GROUPING SETS ( (a, b), a, b, ( ) )
```

2022-05-19 20:51 UTC, wumpz requested changes

2022-05-19 20:51 UTC, wumpz commented on src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
> +              (
Could you more compress this production? There are three nearly identical copies of this inserted block.

2022-05-19 20:51 UTC, wumpz commented on src/test/java/net/sf/jsqlparser/statement/select/HiveTest.java
> +        statement = CCJSqlParserUtil.parse(sql);
This hole parsing process is done using  assertSqlCanBeParsedAndDeparsed. So you could skip it.

2022-05-19 20:52 UTC, wumpz commented
I still do not get the difference to our current grouping sets variant. Could you explain more specific what you want to achieve?

2022-05-20 02:10 UTC, qzchenwl commented
JsqlParser could not parse `SELECT a, b, SUM( c ) FROM tab1 GROUP BY a, b GROUPING SETS ( (a, b), a, b, ( ) )`, it's a legal Hive statement.

It's an equivalent of Presto's `SELECT a, b, SUM( c ) FROM tab1 GROUP BY GROUPING SETS ( (a, b), a, b, ( ) )`.

2022-07-06 19:40 UTC, merged