fix: tables not find in parentheses join sql.
JSQLParser/JSqlParser pull request #1956
Opened 2024-02-06 09:11 UTC by Hanchers

to fix bug #1955

2024-02-06 10:16 UTC, manticore-projects commented
Thank you for your contribution and the fix, please see my comments.

2024-02-06 15:59 UTC, Hanchers commented
> Thank you for your contribution and the fix, please see my comments. The Spotless Formatter also raised concerns.

fix and please review again

2024-02-07 03:20 UTC, manticore-projects commented
> > Thank you for your contribution and the fix, please see my comments. The Spotless Formatter also raised concerns.
> 
> fix and please review again

I still see the "star" imports, please import Classes explicitly instead.

2024-02-07 04:30 UTC, Hanchers commented
> > > Thank you for your contribution and the fix, please see my comments. The Spotless Formatter also raised concerns.
> > 
> > 
> > fix and please review again
> 
> I still see the "star" imports, please import Classes explicitly instead.

sorry, my idea have a auto import config that couse the "star" imports.  
this time i fix this question and please review again. 
thanks

2024-02-07 04:35 UTC, manticore-projects requested changes

2024-02-07 04:35 UTC, manticore-projects commented on src/test/java/net/sf/jsqlparser/util/TablesNamesFinderTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Please fix this.

2024-02-07 06:14 UTC, manticore-projects approved these changes

2024-02-07 06:16 UTC, manticore-projects commented
Thank you for the corrections and your contribution. I am going to merge it.

2024-02-07 06:30 UTC, Hanchers commented
> Thank you for the corrections and your contribution. I am going to merge it.

thanks， my pleasure

2024-02-07 08:49 UTC, merged