support custom where sql construction logic
JSQLParser/JSqlParser pull request #2010
Opened 2024-05-23 12:30 UTC by redkale

I hope that XxxDeParser can overload this part of the logic when building the where condition sql statement. My requirement is to dynamically build the filter conditions in where according to the parameters.

2024-05-24 02:06 UTC, manticore-projects requested changes
Thank you for your contribution. Please consider the recommended changes and then I would merge it.

2024-05-24 02:06 UTC, manticore-projects commented on src/main/java/net/sf/jsqlparser/util/deparser/DeleteDeParser.java
> +    protected ExpressionVisitor expressionVisitor = new ExpressionVisitorAdapter();
why do we change that to `protected` when there are public getters and setters?

2024-05-24 02:06 UTC, manticore-projects commented on src/main/java/net/sf/jsqlparser/util/deparser/DeleteDeParser.java
> +    protected void acceptWhere(Delete delete) {
ok, but please rename into something like `deparsWhereClause` to stick with the established naming convention.
`accept` implies the visitor pattern which is not applicable here.

2024-05-24 02:06 UTC, manticore-projects commented on src/main/java/net/sf/jsqlparser/util/deparser/MergeDeParser.java
> +    protected final ExpressionDeParser expressionDeParser;
should be kept `private`

2024-05-24 02:06 UTC, manticore-projects commented on src/main/java/net/sf/jsqlparser/util/deparser/MergeDeParser.java
> +    protected final SelectDeParser selectDeParser;
should be kept `private`

2024-05-24 02:06 UTC, manticore-projects commented on src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
> +    protected void acceptWhere(PlainSelect plainSelect) {
should probably be moved into the abstract class instead of re-implementing it several times.

2024-05-24 05:43 UTC, redkale commented
@manticore-projects  thanks, updated
My requirement scenario is ：
 sql template  "SELECT * FROM user WHERE name = :param_name AND status = :param_status"
where param_name  and param_status both is null,  need generated sql: "SELECT * FROM user"
where param_name is not null, param_status  is null,  need generated sql: "SELECT * FROM user WHERE name = ? "
so deParse where expression maybe is empty

2024-05-25 01:41 UTC, manticore-projects commented
> sql template "SELECT * FROM user WHERE name = :param_name AND status = :param_status"

Greetings.

In my opinion, your approach is flawed. Instead of tampering with the `WHERE` clause, you will need to filter for the `JDBCNamedParameter`, then check it's parent AST Node and when it's an `EqualTo` rewrite it into an `IsNull`. 
Alternatively you can rewrite any `EqualTo` Expression into an `IsNull` Expression when the Left or Right Expression is a Null Value.

Those are specific solutions though that won't fit well into the generic de-parser.

2024-05-25 01:46 UTC, manticore-projects requested changes
I won't agree with the StringBuffer based `WHERE` clause exception. Rest is ok though and I would merge it.

2024-05-25 01:46 UTC, manticore-projects commented on src/main/java/net/sf/jsqlparser/util/deparser/DeleteDeParser.java
> +            int len = buffer.length();
Please remove those specific parts from the PR as it does not fit into the generic Deparser.

2024-05-25 01:46 UTC, manticore-projects commented on src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
> +            int len = buffer.length();
Please remove those specific parts from the PR as it does not fit into the generic Deparser.

2024-05-25 01:46 UTC, manticore-projects commented on src/main/java/net/sf/jsqlparser/util/deparser/UpdateDeParser.java
> +            int len = buffer.length();
Please remove those specific parts from the PR as it does not fit into the generic Deparser.

2024-05-25 03:10 UTC, manticore-projects commented
Please fix QA exceptions and then I would merge.

2024-05-25 03:12 UTC, redkale commented
@manticore-projects    thanks,  I add  deparseWhereClause like before。
Statement will be caching, it cannot modify.  generate a new sql template based on parameters， like this:
`class SqlTemple {

    private final Statement sqlStatement;

    public SqlTemple() throws ParseException {
        String sql = "SELECT * FROM user WHERE name = :param_name AND status = :param_status";
        CCJSqlParser sqlParser = new CCJSqlParser(sql).withAllowComplexParsing(true);
        this.sqlStatement = sqlParser.SingleStatement();
    }
    
    public String createJdbcSql(Map<String, Object> map) {
        StringBuilder buffer = new StringBuilder();
        NativeExprDeParser myParser = new NativeExprDeParser(buffer, map);
        SelectDeParser parser = new SelectDeParser();
        StatementDeParser deParser = new StatementDeParser(myParser, parser, buffer);
        sqlStatement.accept(deParser);
        //map is empty  return "SELECT * FROM user"
        //map is {"param_name":"aa"}  reutrn "SELECT * FROM user WHERE name = :param_name"
        //map is {"param_status":2}  reutrn "SELECT * FROM user WHERE status = :param_status"
        //map is {"param_name":"aa","param_status":2}  reutrn "SELECT * FROM user WHERE name = :param_name AND status = :param_status"
        return buffer.toString();
    }

}`

2024-05-25 03:41 UTC, redkale commented
My framework source:  https://github.com/redkale/redkale-plugins/tree/main/src/main/java/org/redkalex/source/parser
@manticore-projects 
The function I designed is to define a SQL with full filtering conditions, and then dynamically build a new SQL with where conditions based on the existence of parameters.
Constructing the sql string into a Statement consumes performance and requires caching the Statement. In StatementDeParser, only the buffer can be dynamically controlled, so I want to dynamically adjust the buffer, not the AST Node.
```java
public interface ForumInfoMapper extends BaseMapper<ForumInfo> {

    @Sql("SELECT f.forum_groupid, s.forum_section_color "
        + "FROM forum_info f, forum_section s "
        + " WHERE f.forumid = s.forumid AND "
        + "s.forum_sectionid = #{bean.forumSectionid} AND "
        + "f.forumid = #{bean.forumid} AND s.forum_section_color = #{bean.forumSectionColor}")
    public ForumResult findForumResult(ForumBean bean);

    @Sql("SELECT f.forum_groupid, s.forum_section_color "
        + "FROM forum_info f, forum_section s "
        + " WHERE f.forumid = s.forumid AND "
        + "s.forum_sectionid = #{bean.forumSectionid} AND "
        + "f.forumid = #{bean.forumid} AND s.forum_section_color = #{bean.forumSectionColor}")
    public CompletableFuture<ForumResult> findForumResultAsync(ForumBean bean);
}
```

2024-05-25 10:40 UTC, manticore-projects commented
QA still failing.
Run './gradlew :spotlessApply' to fix these violations.

2024-05-25 23:54 UTC, manticore-projects commented
Before you push, please run the QA locally via `gradle check`.

2024-05-26 00:07 UTC, manticore-projects commented
Although I still believe that your approach is not best practise. Rather than tampering with the `WHERE` clause I would rewrite the query like:

```sql
select *
from t
where ( :param1 is null or column1= :param1) AND ( :param2 IS NULL or column2 = :param2 )
```

Then you can set the parameters `:param1` or `:param2` to NULL when not provided in your Parameter Map.
You may want to have a look at https://manticore-projects.com/MJdbcUtils/index.html which I wrote for exactly this purpose.

2024-05-27 12:21 UTC, closed without merging